-- schema.sql

CREATE TABLE IF NOT EXISTS Products (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FD_NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS InwardTransactions (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  DateTime TEXT NOT NULL,
  FD_NAME TEXT NOT NULL,
  Pouch_Date TEXT NOT NULL,
  Num_Pouches INTEGER NOT NULL,
  Qty_GM INTEGER NOT NULL,
  Remarks TEXT,
  FOREIGN KEY (FD_NAME) REFERENCES Products(FD_NAME)
);

CREATE TABLE IF NOT EXISTS DispatchTransactions (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  DateTime TEXT NOT NULL,
  FD_NAME TEXT NOT NULL,
  Pouch_Date TEXT NOT NULL,
  Num_Pouches INTEGER NOT NULL,
  Qty_GM INTEGER NOT NULL,
  Remarks TEXT,
  FOREIGN KEY (FD_NAME) REFERENCES Products(FD_NAME)
);
